//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenoExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int id_detalle_factura { get; set; }
        public int id_encabezado_factura { get; set; }
        public string id_producto { get; set; }
        public int cantidad { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual ENCABEZADO_FACTURA ENCABEZADO_FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
